apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-feature-discovery

bases:
- ../../base/rbac
- ../../base/rbac-topologyupdater
- ../../base/master
- ../../base/noderesourcetopologies-crd
- ../../base/topologyupdater-daemonset

resources:
- namespace.yaml

components:
- ../../components/common
- ../../components/topology-updater
